version: "3.9"

services:

  job-search-ai:

    build: .

    container_name: job-search-ai

    restart: always

    depends_on:
      - ollama

    ports:
      - "8000:8000"

    volumes:
      - ./uploads:/app/uploads
      - ./database.db:/app/database.db

    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=phi3

    networks:
      - devops-network


  ollama:

    image: ollama/ollama:latest

    container_name: ollama

    restart: always

    ports:
      - "11434:11434"

    volumes:
      - ollama-data:/root/.ollama

    networks:
      - devops-network


volumes:
  ollama-data:


networks:

  devops-network:
