version: "3.9"

services:

  job-search-ai:

    build: .

    container_name: job-search-ai

    restart: always

    ports:
      - "8000:8000"

    volumes:
      - ./uploads:/app/uploads
      - ./database.db:/app/database.db

    environment:
      - PYTHONUNBUFFERED=1

    networks:
      - devops-network

networks:

  devops-network:
