apiVersion: v1
kind: ConfigMap
metadata:
  name: job-search-ai-config
  namespace: job-search-ai

data:
  APP_NAME: "Job Search AI"
  ENVIRONMENT: "development"
  LOG_LEVEL: "INFO"

data:
  OLLAMA_URL: "http://ollama-service:11434/api/generate"
  OLLAMA_MODEL: "phi3"
  PYTHONUNBUFFERED: "1"
