apiVersion: v1
kind: Service
metadata:
  name: job-search-ai-service

spec:
  type: NodePort

  selector:
    app: job-search-ai

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
